
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Fixed @fixed;
	private global::Gtk.Frame frameFileList;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView tree;
	private global::Gtk.Label GtkLabelFileList;
	private global::Gtk.Frame frameGeneral;
	private global::Gtk.Alignment GtkAlignment1;
	private global::MediaConvertGUI.WidgetGeneralMediaInfo widgetGenera;
	private global::Gtk.Label GtkLabelFrameGeneral;
	private global::Gtk.Frame frameVideo;
	private global::Gtk.Alignment GtkAlignment2;
	private global::MediaConvertGUI.WidgetMovieTrack widgetmovietrack;
	private global::Gtk.Label GtkLabelSourceVideoFrame;
	private global::Gtk.Frame frameAudioTracks;
	private global::Gtk.Alignment GtkAlignment5;
	private global::MediaConvertGUI.WidgetAudioTracks widgetaudiotracks;
	private global::Gtk.Label GtkLabelAidoTracks;
	private global::Gtk.Frame frameTargetVideo;
	private global::Gtk.Alignment GtkAlignment6;
	private global::MediaConvertGUI.WidgetMovieTrack widgetTargetMovieTrack;
	private global::Gtk.Label GtkLabelTargetFrameLabel;
	private global::Gtk.Button buttonAdd;
	private global::Gtk.Frame frameTargetAudio;
	private global::Gtk.Alignment GtkAlignment10;
	private global::MediaConvertGUI.WidgetTargetAudioTrack widgetTargetAudioTrack;
	private global::Gtk.Label GtkLabelTargetAudoTracks;
	private global::Gtk.Button buttonGoConvert;
	private global::Gtk.Button buttonRemove;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Media Convert");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.@fixed = new global::Gtk.Fixed ();
		this.@fixed.WidthRequest = 350;
		this.@fixed.Name = "fixed";
		this.@fixed.HasWindow = false;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameFileList = new global::Gtk.Frame ();
		this.frameFileList.WidthRequest = 640;
		this.frameFileList.HeightRequest = 100;
		this.frameFileList.Name = "frameFileList";
		this.frameFileList.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frameFileList.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tree = new global::Gtk.TreeView ();
		this.tree.WidthRequest = 300;
		this.tree.CanFocus = true;
		this.tree.Name = "tree";
		this.GtkScrolledWindow.Add (this.tree);
		this.GtkAlignment3.Add (this.GtkScrolledWindow);
		this.frameFileList.Add (this.GtkAlignment3);
		this.GtkLabelFileList = new global::Gtk.Label ();
		this.GtkLabelFileList.Name = "GtkLabelFileList";
		this.GtkLabelFileList.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>File list</b>");
		this.GtkLabelFileList.UseMarkup = true;
		this.frameFileList.LabelWidget = this.GtkLabelFileList;
		this.@fixed.Add (this.frameFileList);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameFileList]));
		w5.X = 5;
		w5.Y = 5;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameGeneral = new global::Gtk.Frame ();
		this.frameGeneral.Name = "frameGeneral";
		this.frameGeneral.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frameGeneral.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.WidthRequest = 600;
		this.GtkAlignment1.HeightRequest = 40;
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.widgetGenera = new global::MediaConvertGUI.WidgetGeneralMediaInfo ();
		this.widgetGenera.HeightRequest = 100;
		this.widgetGenera.Events = ((global::Gdk.EventMask)(256));
		this.widgetGenera.Name = "widgetGenera";
		this.GtkAlignment1.Add (this.widgetGenera);
		this.frameGeneral.Add (this.GtkAlignment1);
		this.GtkLabelFrameGeneral = new global::Gtk.Label ();
		this.GtkLabelFrameGeneral.Name = "GtkLabelFrameGeneral";
		this.GtkLabelFrameGeneral.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General</b>");
		this.GtkLabelFrameGeneral.UseMarkup = true;
		this.frameGeneral.LabelWidget = this.GtkLabelFrameGeneral;
		this.@fixed.Add (this.frameGeneral);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameGeneral]));
		w8.X = 5;
		w8.Y = 110;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameVideo = new global::Gtk.Frame ();
		this.frameVideo.WidthRequest = 350;
		this.frameVideo.HeightRequest = 280;
		this.frameVideo.Name = "frameVideo";
		// Container child frameVideo.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.widgetmovietrack = new global::MediaConvertGUI.WidgetMovieTrack ();
		this.widgetmovietrack.Events = ((global::Gdk.EventMask)(256));
		this.widgetmovietrack.Name = "widgetmovietrack";
		this.widgetmovietrack.Editable = false;
		this.GtkAlignment2.Add (this.widgetmovietrack);
		this.frameVideo.Add (this.GtkAlignment2);
		this.GtkLabelSourceVideoFrame = new global::Gtk.Label ();
		this.GtkLabelSourceVideoFrame.Name = "GtkLabelSourceVideoFrame";
		this.GtkLabelSourceVideoFrame.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Source video track</b>");
		this.GtkLabelSourceVideoFrame.UseMarkup = true;
		this.frameVideo.LabelWidget = this.GtkLabelSourceVideoFrame;
		this.@fixed.Add (this.frameVideo);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameVideo]));
		w11.X = 5;
		w11.Y = 170;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameAudioTracks = new global::Gtk.Frame ();
		this.frameAudioTracks.WidthRequest = 350;
		this.frameAudioTracks.HeightRequest = 210;
		this.frameAudioTracks.Name = "frameAudioTracks";
		// Container child frameAudioTracks.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.widgetaudiotracks = new global::MediaConvertGUI.WidgetAudioTracks ();
		this.widgetaudiotracks.Events = ((global::Gdk.EventMask)(256));
		this.widgetaudiotracks.Name = "widgetaudiotracks";
		this.widgetaudiotracks.Editable = false;
		this.GtkAlignment5.Add (this.widgetaudiotracks);
		this.frameAudioTracks.Add (this.GtkAlignment5);
		this.GtkLabelAidoTracks = new global::Gtk.Label ();
		this.GtkLabelAidoTracks.Name = "GtkLabelAidoTracks";
		this.GtkLabelAidoTracks.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Source audio track(s)</b>");
		this.GtkLabelAidoTracks.UseMarkup = true;
		this.frameAudioTracks.LabelWidget = this.GtkLabelAidoTracks;
		this.@fixed.Add (this.frameAudioTracks);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameAudioTracks]));
		w14.X = 7;
		w14.Y = 460;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameTargetVideo = new global::Gtk.Frame ();
		this.frameTargetVideo.WidthRequest = 350;
		this.frameTargetVideo.HeightRequest = 280;
		this.frameTargetVideo.Name = "frameTargetVideo";
		// Container child frameTargetVideo.Gtk.Container+ContainerChild
		this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment6.Name = "GtkAlignment6";
		this.GtkAlignment6.LeftPadding = ((uint)(12));
		// Container child GtkAlignment6.Gtk.Container+ContainerChild
		this.widgetTargetMovieTrack = new global::MediaConvertGUI.WidgetMovieTrack ();
		this.widgetTargetMovieTrack.Events = ((global::Gdk.EventMask)(256));
		this.widgetTargetMovieTrack.Name = "widgetTargetMovieTrack";
		this.widgetTargetMovieTrack.Editable = false;
		this.GtkAlignment6.Add (this.widgetTargetMovieTrack);
		this.frameTargetVideo.Add (this.GtkAlignment6);
		this.GtkLabelTargetFrameLabel = new global::Gtk.Label ();
		this.GtkLabelTargetFrameLabel.Name = "GtkLabelTargetFrameLabel";
		this.GtkLabelTargetFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Target video track</b>");
		this.GtkLabelTargetFrameLabel.UseMarkup = true;
		this.frameTargetVideo.LabelWidget = this.GtkLabelTargetFrameLabel;
		this.@fixed.Add (this.frameTargetVideo);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameTargetVideo]));
		w17.X = 380;
		w17.Y = 170;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.WidthRequest = 35;
		this.buttonAdd.HeightRequest = 35;
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		// Container child buttonAdd.Gtk.Container+ContainerChild
		global::Gtk.Alignment w18 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w19 = new global::Gtk.HBox ();
		w19.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w20 = new global::Gtk.Image ();
		w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w19.Add (w20);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w22 = new global::Gtk.Label ();
		w19.Add (w22);
		w18.Add (w19);
		this.buttonAdd.Add (w18);
		this.@fixed.Add (this.buttonAdd);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonAdd]));
		w26.X = 650;
		w26.Y = 18;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.frameTargetAudio = new global::Gtk.Frame ();
		this.frameTargetAudio.WidthRequest = 350;
		this.frameTargetAudio.HeightRequest = 210;
		this.frameTargetAudio.Name = "frameTargetAudio";
		// Container child frameTargetAudio.Gtk.Container+ContainerChild
		this.GtkAlignment10 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment10.Name = "GtkAlignment10";
		this.GtkAlignment10.LeftPadding = ((uint)(12));
		// Container child GtkAlignment10.Gtk.Container+ContainerChild
		this.widgetTargetAudioTrack = new global::MediaConvertGUI.WidgetTargetAudioTrack ();
		this.widgetTargetAudioTrack.Events = ((global::Gdk.EventMask)(256));
		this.widgetTargetAudioTrack.Name = "widgetTargetAudioTrack";
		this.GtkAlignment10.Add (this.widgetTargetAudioTrack);
		this.frameTargetAudio.Add (this.GtkAlignment10);
		this.GtkLabelTargetAudoTracks = new global::Gtk.Label ();
		this.GtkLabelTargetAudoTracks.Name = "GtkLabelTargetAudoTracks";
		this.GtkLabelTargetAudoTracks.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Target audio track</b>");
		this.GtkLabelTargetAudoTracks.UseMarkup = true;
		this.frameTargetAudio.LabelWidget = this.GtkLabelTargetAudoTracks;
		this.@fixed.Add (this.frameTargetAudio);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameTargetAudio]));
		w29.X = 380;
		w29.Y = 460;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.buttonGoConvert = new global::Gtk.Button ();
		this.buttonGoConvert.WidthRequest = 720;
		this.buttonGoConvert.CanFocus = true;
		this.buttonGoConvert.Name = "buttonGoConvert";
		this.buttonGoConvert.UseUnderline = true;
		this.buttonGoConvert.Label = global::Mono.Unix.Catalog.GetString ("Go");
		this.@fixed.Add (this.buttonGoConvert);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonGoConvert]));
		w30.X = 10;
		w30.Y = 680;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.buttonRemove = new global::Gtk.Button ();
		this.buttonRemove.WidthRequest = 35;
		this.buttonRemove.HeightRequest = 35;
		this.buttonRemove.CanFocus = true;
		this.buttonRemove.Name = "buttonRemove";
		this.buttonRemove.UseUnderline = true;
		// Container child buttonRemove.Gtk.Container+ContainerChild
		global::Gtk.Alignment w31 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w32 = new global::Gtk.HBox ();
		w32.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w33 = new global::Gtk.Image ();
		w33.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
		w32.Add (w33);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w35 = new global::Gtk.Label ();
		w32.Add (w35);
		w31.Add (w32);
		this.buttonRemove.Add (w31);
		this.@fixed.Add (this.buttonRemove);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonRemove]));
		w39.X = 690;
		w39.Y = 18;
		this.Add (this.@fixed);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 744;
		this.DefaultHeight = 748;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.tree.CursorChanged += new global::System.EventHandler (this.OnTreeCursorChanged);
		this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
		this.buttonGoConvert.Clicked += new global::System.EventHandler (this.OnButtonGoConvertClicked);
		this.buttonRemove.Clicked += new global::System.EventHandler (this.OnButtonRemoveClicked);
	}
}
