
// This file has been generated by the GUI designer. Do not modify.
namespace MediaConvertGUI
{
	public partial class ProgressWin
	{
		private global::Gtk.Fixed @fixed;
		private global::Gtk.Label labelTimeElapsed;
		private global::Gtk.Label labelTimeRemain;
		private global::Gtk.Label labelTimeTotal;
		private global::Gtk.Label labelElapsed;
		private global::Gtk.Label labelRemain;
		private global::Gtk.Label labelTotal;
		private global::Gtk.Label labelStartTime;
		private global::Gtk.Label labelFinishTime;
		private global::Gtk.Label labelStart;
		private global::Gtk.Label labelFinish;
		private global::Gtk.Label labelCurrentFilePercents;
		private global::Gtk.Button buttonAbort;
		private global::Gtk.Button buttonClose;
		private global::Gtk.Label labelAll;
		private global::Gtk.Label labelCurrentFile;
		private global::Gtk.Label labelCurrentPass;
		private global::Gtk.ProgressBar progressTotal;
		private global::Gtk.ProgressBar progressCurrentFile;
		private global::Gtk.ProgressBar progressCurrentPass;
		private global::Gtk.Label labelCurrentPassPercents;
		private global::Gtk.Label labelTotalPercents;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MediaConvertGUI.ProgressWin
			this.Name = "MediaConvertGUI.ProgressWin";
			this.Title = global::Mono.Unix.Catalog.GetString ("Progess");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MediaConvertGUI.ProgressWin.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTimeElapsed = new global::Gtk.Label ();
			this.labelTimeElapsed.Name = "labelTimeElapsed";
			this.labelTimeElapsed.LabelProp = global::Mono.Unix.Catalog.GetString ("Time elapsed");
			this.@fixed.Add (this.labelTimeElapsed);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTimeElapsed]));
			w1.X = 15;
			w1.Y = 110;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTimeRemain = new global::Gtk.Label ();
			this.labelTimeRemain.Name = "labelTimeRemain";
			this.labelTimeRemain.LabelProp = global::Mono.Unix.Catalog.GetString ("Time remain");
			this.@fixed.Add (this.labelTimeRemain);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTimeRemain]));
			w2.X = 15;
			w2.Y = 130;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTimeTotal = new global::Gtk.Label ();
			this.labelTimeTotal.Name = "labelTimeTotal";
			this.labelTimeTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Time total");
			this.@fixed.Add (this.labelTimeTotal);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTimeTotal]));
			w3.X = 15;
			w3.Y = 150;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelElapsed = new global::Gtk.Label ();
			this.labelElapsed.Name = "labelElapsed";
			this.labelElapsed.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
			this.@fixed.Add (this.labelElapsed);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelElapsed]));
			w4.X = 120;
			w4.Y = 110;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelRemain = new global::Gtk.Label ();
			this.labelRemain.Name = "labelRemain";
			this.labelRemain.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
			this.@fixed.Add (this.labelRemain);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelRemain]));
			w5.X = 120;
			w5.Y = 130;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTotal = new global::Gtk.Label ();
			this.labelTotal.Name = "labelTotal";
			this.labelTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
			this.@fixed.Add (this.labelTotal);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTotal]));
			w6.X = 120;
			w6.Y = 150;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelStartTime = new global::Gtk.Label ();
			this.labelStartTime.Name = "labelStartTime";
			this.labelStartTime.LabelProp = global::Mono.Unix.Catalog.GetString ("Started");
			this.@fixed.Add (this.labelStartTime);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelStartTime]));
			w7.X = 15;
			w7.Y = 90;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelFinishTime = new global::Gtk.Label ();
			this.labelFinishTime.Name = "labelFinishTime";
			this.labelFinishTime.LabelProp = global::Mono.Unix.Catalog.GetString ("Finish");
			this.@fixed.Add (this.labelFinishTime);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelFinishTime]));
			w8.X = 15;
			w8.Y = 170;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelStart = new global::Gtk.Label ();
			this.labelStart.Name = "labelStart";
			this.labelStart.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
			this.@fixed.Add (this.labelStart);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelStart]));
			w9.X = 120;
			w9.Y = 90;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelFinish = new global::Gtk.Label ();
			this.labelFinish.Name = "labelFinish";
			this.labelFinish.LabelProp = global::Mono.Unix.Catalog.GetString ("00:00:00");
			this.@fixed.Add (this.labelFinish);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelFinish]));
			w10.X = 120;
			w10.Y = 170;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelCurrentFilePercents = new global::Gtk.Label ();
			this.labelCurrentFilePercents.Name = "labelCurrentFilePercents";
			this.labelCurrentFilePercents.LabelProp = global::Mono.Unix.Catalog.GetString ("0%");
			this.@fixed.Add (this.labelCurrentFilePercents);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelCurrentFilePercents]));
			w11.X = 410;
			w11.Y = 35;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.buttonAbort = new global::Gtk.Button ();
			this.buttonAbort.CanFocus = true;
			this.buttonAbort.Name = "buttonAbort";
			this.buttonAbort.UseUnderline = true;
			// Container child buttonAbort.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-stop", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Abort");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.buttonAbort.Add (w12);
			this.@fixed.Add (this.buttonAbort);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonAbort]));
			w20.X = 310;
			w20.Y = 210;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			// Container child buttonClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Close");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.buttonClose.Add (w21);
			this.@fixed.Add (this.buttonClose);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonClose]));
			w29.X = 380;
			w29.Y = 210;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelAll = new global::Gtk.Label ();
			this.labelAll.Name = "labelAll";
			this.labelAll.LabelProp = global::Mono.Unix.Catalog.GetString ("Overall");
			this.@fixed.Add (this.labelAll);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelAll]));
			w30.X = 15;
			w30.Y = 10;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelCurrentFile = new global::Gtk.Label ();
			this.labelCurrentFile.Name = "labelCurrentFile";
			this.labelCurrentFile.LabelProp = global::Mono.Unix.Catalog.GetString ("Current file");
			this.@fixed.Add (this.labelCurrentFile);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelCurrentFile]));
			w31.X = 15;
			w31.Y = 35;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelCurrentPass = new global::Gtk.Label ();
			this.labelCurrentPass.Name = "labelCurrentPass";
			this.labelCurrentPass.LabelProp = global::Mono.Unix.Catalog.GetString ("Current pass");
			this.@fixed.Add (this.labelCurrentPass);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelCurrentPass]));
			w32.X = 15;
			w32.Y = 60;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.progressTotal = new global::Gtk.ProgressBar ();
			this.progressTotal.WidthRequest = 280;
			this.progressTotal.Name = "progressTotal";
			this.@fixed.Add (this.progressTotal);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.progressTotal]));
			w33.X = 120;
			w33.Y = 10;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.progressCurrentFile = new global::Gtk.ProgressBar ();
			this.progressCurrentFile.WidthRequest = 280;
			this.progressCurrentFile.Name = "progressCurrentFile";
			this.@fixed.Add (this.progressCurrentFile);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.progressCurrentFile]));
			w34.X = 120;
			w34.Y = 35;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.progressCurrentPass = new global::Gtk.ProgressBar ();
			this.progressCurrentPass.WidthRequest = 280;
			this.progressCurrentPass.Name = "progressCurrentPass";
			this.@fixed.Add (this.progressCurrentPass);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.progressCurrentPass]));
			w35.X = 120;
			w35.Y = 60;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelCurrentPassPercents = new global::Gtk.Label ();
			this.labelCurrentPassPercents.Name = "labelCurrentPassPercents";
			this.labelCurrentPassPercents.LabelProp = global::Mono.Unix.Catalog.GetString ("0%");
			this.@fixed.Add (this.labelCurrentPassPercents);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelCurrentPassPercents]));
			w36.X = 410;
			w36.Y = 60;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTotalPercents = new global::Gtk.Label ();
			this.labelTotalPercents.Name = "labelTotalPercents";
			this.labelTotalPercents.LabelProp = global::Mono.Unix.Catalog.GetString ("0%");
			this.@fixed.Add (this.labelTotalPercents);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTotalPercents]));
			w37.X = 410;
			w37.Y = 10;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 474;
			this.DefaultHeight = 275;
			this.Show ();
			this.buttonAbort.Clicked += new global::System.EventHandler (this.OnButtonAbortClicked);
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
		}
	}
}
