
// This file has been generated by the GUI designer. Do not modify.
namespace MediaConvertGUI
{
	public partial class WidgetTargetAudioTrack
	{
		private global::Gtk.Fixed @fixed;
		private global::Gtk.Label labelAudioInfo;
		private global::Gtk.ComboBox comboAudio;
		private global::Gtk.Frame frameAudio;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label labelBitrate;
		private global::Gtk.Label labelChannels;
		private global::Gtk.Label labelSampleRate;
		private global::Gtk.Label labelTrackSizeInfo;
		private global::Gtk.ComboBox comboChannels;
		private global::Gtk.ComboBoxEntry comboSampleRate;
		private global::Gtk.Label labelKhz;
		private global::Gtk.Label labelTrackSize;
		private global::Gtk.ComboBoxEntry comboBitRate;
		private global::Gtk.Label GtkLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MediaConvertGUI.WidgetTargetAudioTrack
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MediaConvertGUI.WidgetTargetAudioTrack";
			// Container child MediaConvertGUI.WidgetTargetAudioTrack.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelAudioInfo = new global::Gtk.Label ();
			this.labelAudioInfo.Name = "labelAudioInfo";
			this.labelAudioInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Audio");
			this.@fixed.Add (this.labelAudioInfo);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelAudioInfo]));
			w1.X = 5;
			w1.Y = 10;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.comboAudio = global::Gtk.ComboBox.NewText ();
			this.comboAudio.Name = "comboAudio";
			this.@fixed.Add (this.comboAudio);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.comboAudio]));
			w2.X = 50;
			w2.Y = 5;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.frameAudio = new global::Gtk.Frame ();
			this.frameAudio.WidthRequest = 300;
			this.frameAudio.HeightRequest = 150;
			this.frameAudio.Name = "frameAudio";
			this.frameAudio.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameAudio.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelBitrate = new global::Gtk.Label ();
			this.labelBitrate.Name = "labelBitrate";
			this.labelBitrate.LabelProp = global::Mono.Unix.Catalog.GetString ("Bitrate");
			this.fixed1.Add (this.labelBitrate);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelBitrate]));
			w3.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelChannels = new global::Gtk.Label ();
			this.labelChannels.Name = "labelChannels";
			this.labelChannels.LabelProp = global::Mono.Unix.Catalog.GetString ("Channels");
			this.fixed1.Add (this.labelChannels);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelChannels]));
			w4.Y = 35;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelSampleRate = new global::Gtk.Label ();
			this.labelSampleRate.Name = "labelSampleRate";
			this.labelSampleRate.LabelProp = global::Mono.Unix.Catalog.GetString ("Sample rate");
			this.fixed1.Add (this.labelSampleRate);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelSampleRate]));
			w5.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelTrackSizeInfo = new global::Gtk.Label ();
			this.labelTrackSizeInfo.Name = "labelTrackSizeInfo";
			this.labelTrackSizeInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Track size");
			this.fixed1.Add (this.labelTrackSizeInfo);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelTrackSizeInfo]));
			w6.Y = 95;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboChannels = global::Gtk.ComboBox.NewText ();
			this.comboChannels.Name = "comboChannels";
			this.fixed1.Add (this.comboChannels);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboChannels]));
			w7.X = 110;
			w7.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboSampleRate = global::Gtk.ComboBoxEntry.NewText ();
			this.comboSampleRate.WidthRequest = 100;
			this.comboSampleRate.Name = "comboSampleRate";
			this.fixed1.Add (this.comboSampleRate);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboSampleRate]));
			w8.X = 110;
			w8.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelKhz = new global::Gtk.Label ();
			this.labelKhz.Name = "labelKhz";
			this.labelKhz.LabelProp = global::Mono.Unix.Catalog.GetString ("Khz");
			this.fixed1.Add (this.labelKhz);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelKhz]));
			w9.X = 220;
			w9.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelTrackSize = new global::Gtk.Label ();
			this.labelTrackSize.Name = "labelTrackSize";
			this.labelTrackSize.LabelProp = global::Mono.Unix.Catalog.GetString ("0 MB");
			this.fixed1.Add (this.labelTrackSize);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelTrackSize]));
			w10.X = 110;
			w10.Y = 95;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboBitRate = global::Gtk.ComboBoxEntry.NewText ();
			this.comboBitRate.WidthRequest = 100;
			this.comboBitRate.Name = "comboBitRate";
			this.fixed1.Add (this.comboBitRate);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboBitRate]));
			w11.X = 110;
			this.GtkAlignment.Add (this.fixed1);
			this.frameAudio.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b></b>");
			this.GtkLabel.UseMarkup = true;
			this.frameAudio.LabelWidget = this.GtkLabel;
			this.@fixed.Add (this.frameAudio);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.frameAudio]));
			w14.X = 5;
			w14.Y = 35;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboAudio.Changed += new global::System.EventHandler (this.OnComboAudioChanged);
			this.comboChannels.Changed += new global::System.EventHandler (this.OnComboChannelsChanged);
			this.comboSampleRate.Changed += new global::System.EventHandler (this.OnComboSampleRateChanged);
			this.comboBitRate.Changed += new global::System.EventHandler (this.OnComboBitRateChanged);
		}
	}
}
